# apiserver gets the auth-delegator role to delegate auth decisions to
# the core apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cert-manager-webhook-alidns.fullname" . }}:auth-delegator
  labels:
    app: {{ include "cert-manager-webhook-alidns.name" . }}
    chart: {{ include "cert-manager-webhook-alidns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "cert-manager-webhook-alidns.fullname" . }}
    namespace: {{ .Release.Namespace }}